version: "2"
services:
  mysql:
    container_name: contributte-datagrid-mysql
    image: mysql:5.6
    ports:
      - 20002:3306
    volumes:
      - ./_data/mysql:/var/lib/mysql
      - ./data:/usr/share/datagrid
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
